ia:
  url: https://generativelanguage.googleapis.com/v1beta/tunedModels
  #  model: settlement-combinations-v01-kvqvb3romxts
#  model: settlement-combinations-v05-cn36fu929vg5
  model: settlement-combinations-v02-cy7ao9x4l9eu
  apiKey: ${AI_API_KEY:''}

spring:
  application:
    name: iob-spring-boilerplate
  datasource:
    eventeum:
      url: jdbc:postgresql://${EVENTEUM_DATABASE_HOST:localhost}:${EVENTEUM_DATABASE_PORT:5432}/${EVENTEUM_DATABASE_DB:eventeum}
      username: ${EVENTEUM_DATABASE_USERNAME:iob}
      password: ${EVENTEUM_DATABASE_PWD:superSecure1!}
      hikari:
        maximum-pool-size: ${EVENTEUM_DATABASE_MAX_POOL_SIZE:10}
        minimum-idle: ${EVENTEUM_DATABASE_MIN_IDLE:5}
        connection-timeout: ${EVENTEUM_DATABASE_TIMEOUT:30000}
    blockchain:
      url: jdbc:postgresql://${BLOCKCHAIN_DATABASE_HOST:localhost}:${BLOCKCHAIN_DATABASE_PORT:5432}/${BLOCKCHAIN_DATABASE_DB:blockchain}
      username: ${BLOCKCHAIN_DATABASE_USERNAME:iob}
      password: ${BLOCKCHAIN_DATABASE_PWD:superSecure1!}
      hikari:
        maximum-pool-size: ${BLOCKCHAIN_DATABASE_MAX_POOL_SIZE:10}
        minimum-idle: ${BLOCKCHAIN_DATABASE_MIN_IDLE:5}
        connection-timeout: ${BLOCKCHAIN_DATABASE_TIMEOUT:30000}
    surikata:
      url: jdbc:postgresql://${SURIKATA_DATABASE_HOST:localhost}:${SURIKATA_DATABASE_PORT:5432}/${SURIKATA_DATABASE_DB:surikata}
      username: ${SURIKATA_DATABASE_USERNAME:iob}
      password: ${SURIKATA_DATABASE_PWD:superSecure1!}
      hikari:
        maximum-pool-size: ${SURIKATA_DATABASE_MAX_POOL_SIZE:10}
        minimum-idle: ${SURIKATA_DATABASE_MIN_IDLE:5}
        connection-timeout: ${SURIKATA_DATABASE_TIMEOUT:30000}
    dtcc:
      url: jdbc:postgresql://${DTCC_DATABASE_HOST:localhost}:${DTCC_DATABASE_PORT:5432}/${DTCC_DATABASE_DB:dtcc}
      username: ${DTCC_DATABASE_USERNAME:iob}
      password: ${DTCC_DATABASE_PWD:superSecure1!}
      hikari:
        maximum-pool-size: ${DTCC_DATABASE_MAX_POOL_SIZE:10}
        minimum-idle: ${DTCC_DATABASE_MIN_IDLE:5}
        connection-timeout: ${DTCC_DATABASE_TIMEOUT:30000}

# Eventeum
eventStore:
  type: DB
  url: ${EVENTEUM_PROTOCOL:http}://${EVENTEUM_HOST:localhost}:${EVENTEUM_PORT:8080}/api/rest/v1/eventeum
  eventPath: /event
  latestBlockPath: /latest-block
database:
  type: SQL

ethereum:
  nodes: []

hashgraph:
  nodes:
    - name: hedera
      type: MIRROR
      url: ${HEDERA_NODE_URL:https://testnet.mirrornode.hedera.com}
      limitPerRequest: 50
      blockStrategy: POLL
      addTransactionRevertReason: true
      pollingInterval: 500
      maxIdleConnections: 10
      keepAliveDuration: 15000
      connectionTimeout: 7000
      readTimeout: 180000
      healthcheckInterval: 5000
      numBlocksToWait: 0
      numBlocksToWaitForMissingTx: 0
      numBlocksToWaitBeforeInvalidating: 0
      maxUnsyncedBlocksForFilter: 50
      syncingThreshold: 100
      initialStartBlock: 15369462

broadcaster:
  enableBlockNotifications: false
  type: ${EVENTEUM_BROADCASTER:HTTP}
  cache:
    expirationMillis: ${EVENTEUM_CACHE_EXPIRATION_IN_MILLIS:1}
  event:
    confirmation:
      numBlocksToWait: ${EVENTEUM_NUM_BLOCKS_TO_WAIT:0}
      numBlocksToWaitForMissingTx: ${EVENTEUM_NUM_BLOCKS_TO_WAIT_FOR_MISSING_TX:100}
      numBlocksToWaitBeforeInvalidating: ${EVENTEUM_NUM_BLOCKS_TO_WAIT_BEFORE_INVALIDATING:2}
  http:
    #    blockEventsUrl: ${HTTP_PROTOCOL_BLOCK_EVENTS_URL:http}://${HTTP_PROTOCOL_BLOCK_EVENTS_HOST:localhost}:${HTTP_PROTOCOL_BLOCK_EVENTS_PORT:8080}/api/v1/listener/block
    contractEventsUrl: ${HTTP_PROTOCOL_CONTRACT_EVENTS_URL:http}://${HTTP_PROTOCOL_CONTRACT_EVENTS_HOST:localhost}:${HTTP_PROTOCOL_CONTRACT_EVENTS_PORT:8080}/api/v1/surikata/contract-events
    transactionEventsUrl: ${HTTP_PROTOCOL_TRANSACTION_EVENTS_URL:http}://${HTTP_PROTOCOL_TRANSACTION_EVENTS_HOST:localhost}:${HTTP_PROTOCOL_TRANSACTION_EVENTS_PORT:8080}/api/v1/surikata/transactions
#    messageEventsUrl: ${HTTP_PROTOCOL_MESSAGE_EVENTS_URL:http}://${HTTP_PROTOCOL_MESSAGE_EVENTS_HOST:localhost}:${HTTP_PROTOCOL_MESSAGE_EVENTS_PORT:8080}/api/v1/message-events

eventFilters:
  - id: DvpOrchestratorLsmExecuted.${CONTRACT_ADDRESS:0x1239E437441f7E2daAC8ecf315f802D589546B04}
    node: ${ETH_NODE:hedera}
    contractAddress: ${CONTRACT_ADDRESS:0x1239E437441f7E2daAC8ecf315f802D589546B04}
    eventSpecification:
      eventName: LsmExecuted
      eventSignature: (uint256,(address,address,uint256,address)[])
      web3EventSmartContractClass: org.iobuilders.dtcc.contracts.DvpOrchestrator
    correlationId:
      type: NON_INDEXED_PARAMETER
      index: 0

transactionFilters:
  - nodeName: ${ETH_NODE:hedera}
    type: "TO_ADDRESS"
    transactionIdentifierValue: ${CONTRACT_ADDRESS:0x1239E437441f7E2daAC8ecf315f802D589546B04}
    statuses: ['FAILED']

# Core
blockchain:
  url: https://testnet.hashio.io/api
  chain-id: ${BLOCKCHAIN_CHAIN_ID:296}
  gas-limit: ${BLOCKCHAIN_GAS_LIMIT:15000000}
  gas-price: ${BLOCKCHAIN_GAS_PRICE:350000000000}
  gas-multiplier: ${BLOCKCHAIN_GAS_MULTIPLIER:1.0}
  contracts:
    matchSettlement:
      address: "${CONTRACT_ADDRESS:0x1239E437441f7E2daAC8ecf315f802D589546B04}"
      contract-class: org.iobuilders.dtcc.contracts.DvpOrchestrator
  default-provider: database

commandBus:
  defaultTimeout: 120s

queryBus:
  defaultTimeout: 120s

surikata:
  event:
    mappers:
      LsmExecuted: io.builders.demo.dtcc.domain.lsmbatch.event.LsmExecutedDltEvent

hedera:
  testnet: ${HEDERA_NODE_TESTNET:true}
  account:
    id: ${HEDERA_ACCOUNT_ID:0.0.5469588}
    privateKey: ${HEDERA_ACCOUNT_PRIVATE_KEY:''}

logging:
  level:
    org.springframework.web: DEBUG
    net.consensys: DEBUG
    net.consensys.configs: ERROR
    org.springframework.amqp: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5p %c: %M - %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5p %c: %M - %m%n"

dtcc:
  defaultAddress: ${DTCC_DEFAULT_ADDRESS:0x708eeb6f709f5138f0f0344e5b6f6ac11ec4a712}
  privateKey: ${DTCC_ACCOUNT_PRIVATE_KEY:''}
  cashToken: ${DTCC_CASH_TOKEN:0x9cECEB96469c6f96276b7dAC8BAA59218762C9F0}
  securityToken: ${DTCC_SECURITY_TOKEN:0xe0732A10Fee16FDca3d1B196b86014F7fcb67Ac3}
  omnibusAccount: ${DTCC_OMNIBUS_ACCOUNT:0x4d4ccf261cc1551920ab72479351c7670a839a5a}
